import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const data=JSON.parse(fs.readFileSync(path.join(root,'src/data/site.json'),'utf8'));
const aniimoIndex=JSON.parse(fs.readFileSync(path.join(root,'src/data/aniimo-index.json'),'utf8'));
const localeFiles=['en.json','zh-CN.json','ja.json'];
const locales=localeFiles.map(f=>JSON.parse(fs.readFileSync(path.join(root,'src/locales',f),'utf8')));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>s.replace(/^\/+|\/+$/g,'');
const urlPath=(l,r='')=>`/${l.prefix?l.prefix+'/':''}${clean(r)}${r&& !r.endsWith('/')?'/':''}`;
const abs=(l,r='')=>data.domain+urlPath(l,r);
const outPath=(l,r='')=>path.join(root,l.prefix,clean(r),'index.html');
const write=(file,text)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text.replace('/site-content.css"','/site-content.css?v=20260831-1"').replace('/app.js"','/app.js?v=20260830-2"'))};
const alternates=route=>locales.map(l=>`<link rel="alternate" hreflang="${l.lang==='zh-CN'?'zh-CN':l.lang}" href="${abs(l,route)}">`).join('')+`<link rel="alternate" hreflang="x-default" href="${abs(locales[0],route)}">`;
const langLinks=(route,l)=>locales.map(x=>`<a${x.lang===l.lang?' class="current"':''} href="${urlPath(x,route)}" hreflang="${x.lang}">${esc(x.label)}</a>`).join('');
const nav=(l,active,route)=>`<header class="topbar"><a class="brand" href="${urlPath(l)}"><span class="brand-mark">A</span><span>Aniimo<span class="brand-dot">.GG</span></span></a><nav aria-label="${esc(l.common.primaryNav)}"><a${active==='home'?' class="active"':''} href="${urlPath(l)}">${esc(l.nav.home)}</a>${['aniimo','tier-list','guides','database','map','tools','news'].map(k=>`<a${active===k?' class="active"':''} href="${urlPath(l,k)}">${esc(l.nav[k==='tier-list'?'tierList':k])}</a>`).join('')}</nav><details class="language-switcher"><summary aria-label="${esc(l.common.language)}">${esc(l.label)} ▾</summary><div>${langLinks(route,l)}</div></details><button class="menu-btn" aria-label="${esc(l.common.menu)}">☰</button></header>`;
const footer=l=>`<footer><a class="brand" href="${urlPath(l)}"><span class="brand-mark">A</span><span>Aniimo<span class="brand-dot">.GG</span></span></a><p>${esc(l.disclaimer)}</p><div><a href="${urlPath(l,'about')}">${esc(l.pages.about.h1)}</a><a href="${urlPath(l,'authors')}">${esc(l.common.authors)}</a><a href="${urlPath(l,'contact')}">${esc(l.common.contact)}</a><a href="${urlPath(l,'privacy')}">${esc(l.common.privacy)}</a><a href="${urlPath(l,'terms')}">${esc(l.common.terms)}</a><a href="https://www.aniimo.com/" rel="nofollow noopener" target="_blank">${esc(l.common.officialSite)} ↗</a></div></footer>`;
const schema=(type,obj)=>`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':type,...obj}).replace(/</g,'\\u003c')}</script>`;
const doc=({l,route,title,description,active,body,type='WebPage',schemaExtra='',noindex=false,image='/assets/og.png',imageWidth=1200,imageHeight=630})=>`<!doctype html><html lang="${l.lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#091d2d"><link rel="icon" type="image/png" href="/assets/favicon.png"><title>${esc(title)}</title><meta name="description" content="${esc(description)}">${noindex?'<meta name="robots" content="noindex,follow">':''}<link rel="canonical" href="${abs(l,route)}">${alternates(route)}<meta property="og:type" content="website"><meta property="og:locale" content="${l.locale}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${abs(l,route)}"><meta property="og:image" content="${data.domain}${image}"><meta property="og:image:width" content="${imageWidth}"><meta property="og:image:height" content="${imageHeight}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${data.domain}${image}"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/site-content.css"><script src="/app.js" defer></script>${schema(type,{name:title,description,url:abs(l,route),inLanguage:l.lang})}${schemaExtra}</head><body>${nav(l,active,route)}<main>${body}</main>${footer(l)}</body></html>`;
const crumbs=(l,items)=>schema('BreadcrumbList',{itemListElement:items.map((x,i)=>({'@type':'ListItem',position:i+1,name:x[0],item:data.domain+x[1]}))});
const related=(l,id)=>{const route=id==='map'?'map':['authors','contact','privacy'].includes(id)?id:`guides/${id}`;const title=id==='map'?l.pages.map.h1:l.guides[id]?.h1||l.pages[id]?.h1||id;return `<a href="${urlPath(l,route)}"><span>${esc(l.nav.guides)}</span><b>${esc(title)}</b><em>→</em></a>`};
const guideMatrix=g=>`${g.evidence?`<aside class="evidence-note"><h2>${esc(g.evidence[0])}</h2><p>${esc(g.evidence[1])}</p><a href="${esc(g.evidence[3])}" rel="nofollow noopener" target="_blank">${esc(g.evidence[2])} ↗</a></aside>`:''}${g.matrix?`<section class="support-matrix"><h2>${esc(g.matrix.title)}</h2><div><table><thead><tr>${g.matrix.headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${g.matrix.rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>${esc(g.matrix.note)}</p></section>`:''}`;
const guideFaq=g=>g.faq?`<section class="article-faq"><h2>FAQ</h2>${g.faq.map((x,i)=>`<details${i===0?' open':''}><summary>${esc(x[0])}</summary><p>${esc(x[1])}</p></details>`).join('')}</section>`:'';
const guideCard=(l,id)=>`<a href="${urlPath(l,'guides/'+id)}"><img src="/assets/guides/${id}-cover.webp" width="1200" height="675" loading="lazy" alt="${esc(l.guides[id].h1)} — ${esc(l.common.guideCover)}"><span>${esc(l.nav.guides)}</span><h2>${esc(l.guides[id].h1)}</h2><p>${esc(l.guides[id].description)}</p></a>`;
const aniimoTable=l=>{const x=l.aniimoIndex;const options=(labels,all)=>`<option value="">${esc(all)}</option>${Object.entries(labels).map(([v,label])=>`<option value="${v}">${esc(label)}</option>`).join('')}`;const rows=aniimoIndex.map(([number,wikiId,name,stage,roles,elements])=>`<tr data-search="${esc(`${number} ${name}`.toLowerCase())}" data-elements="${elements.join(' ')}" data-roles="${roles.join(' ')}" data-stage="${stage}"><td><b>${esc(number)}</b></td><td><a href="https://wiki.aniimo.com/item/${wikiId}" rel="nofollow noopener" target="_blank">${esc(name)} ↗</a></td><td>${elements.map(v=>`<span class="index-tag element-${v}">${esc(x.elementLabels[v]||v)}</span>`).join(' ')}</td><td>${roles.map(v=>`<span class="index-tag role-tag">${esc(x.roleLabels[v]||v)}</span>`).join(' ')}</td><td>${esc(x.stageLabels[String(stage)]||x.unknownStage)}</td></tr>`).join('');return `<section class="aniimo-index" data-showing="${esc(x.showing)}"><h2>${esc(x.title)}</h2><p>${esc(x.note)}</p><div class="index-filters"><label><span>${esc(x.search)}</span><input type="search" class="index-search" placeholder="${esc(x.search)}"></label><label><span>${esc(x.elements)}</span><select class="index-element">${options(x.elementLabels,x.allElements)}</select></label><label><span>${esc(x.roles)}</span><select class="index-role">${options(x.roleLabels,x.allRoles)}</select></label><label><span>${esc(x.stage)}</span><select class="index-stage">${options(x.stageLabels,x.allStages)}</select></label><button type="button" class="index-clear">${esc(x.clear)}</button></div><p class="index-count" role="status">${esc(x.showing.replace('{count}','94'))}</p><p class="index-empty" hidden>${esc(x.noResults)}</p><div class="index-table-wrap"><table><thead><tr><th>${esc(x.number)}</th><th>${esc(x.name)}</th><th>${esc(x.elements)}</th><th>${esc(x.roles)}</th><th>${esc(x.stage)}</th></tr></thead><tbody>${rows}</tbody></table></div></section>`};

for(const l of locales){
  const h=l.home;
  let homeBody=`<section class="hero"><div class="hero-art" aria-hidden="true"></div><div class="hero-content"><div class="eyebrow"><span></span>${esc(h.eyebrow)}</div><h1>${esc(h.h1)}</h1><p>${esc(h.lead)}</p><form class="hero-search" action="${urlPath(l,'guides')}" role="search"><label class="sr-only" for="q-${l.lang}">${esc(l.common.search)}</label><span>⌕</span><input id="q-${l.lang}" name="q" type="search" placeholder="${esc(l.common.search)}"><button>${esc(l.nav.guides)}</button></form></div><div class="hero-stats"><div><strong>9/16</strong><span>${esc(l.common.pcConsole)}</span></div><div><strong>9/23</strong><span>${esc(l.common.mobile)}</span></div><div><strong>6</strong><span>${esc(l.nav.map)}</span></div></div></section><section class="quick section">${['guides/confirmed-aniimo','tier-list','map','guides'].map((r,i)=>`<a href="${urlPath(l,r)}"><i class="${['mint','coral','violet','gold'][i]}">${['◈','⌁','⌖','✦'][i]}</i><span><b>${esc(h.cards[i][0])}</b><small>${esc(h.cards[i][1])}</small></span><em>→</em></a>`).join('')}</section><section class="section guides"><div class="section-head"><div><span>ANIIMO GUIDE</span><h2>${esc(h.section)}</h2><p>${esc(h.sectionLead)}</p></div></div><div class="guide-grid">${['getting-started','core-gameplay','editorial-policy'].map((id,i)=>{const g=l.guides[id];return `<article class="guide-card${i===0?' featured':''}"><div class="card-visual ${['visual-green','visual-blue','visual-coral'][i]}"><div class="orb">${['✦','◉','△'][i]}</div></div><div class="card-body"><div class="meta">${esc(l.common.updated)} · 2026-08-27</div><h3>${esc(g.h1)}</h3><p>${esc(g.description)}</p><a href="${urlPath(l,'guides/'+id)}">${esc(l.common.readMore)} →</a></div></article>`}).join('')}</div></section>`;
  homeBody+=`<section class="home-explainer section">${h.sections.map(x=>`<article><h2>${esc(x[0])}</h2><p>${esc(x[1])}</p><a href="${urlPath(l,x[2])}">${esc(x[3])} →</a></article>`).join('')}</section><section class="home-faq section"><h2>FAQ</h2>${h.faq.map((x,i)=>`<details${i===0?' open':''}><summary>${esc(x[0])}</summary><p>${esc(x[1])}</p></details>`).join('')}</section><section class="home-sources section"><h2>${esc(l.common.officialSource)}</h2><ul>${h.sources.map(x=>`<li><a href="${esc(x[1])}" rel="nofollow noopener" target="_blank">${esc(x[0])} ↗</a></li>`).join('')}</ul></section>`;
  write(outPath(l),doc({l,route:'',title:h.title,description:h.description,active:'home',body:homeBody,type:'WebSite',schemaExtra:schema('Organization',{name:'Aniimo Guide',url:data.domain})+schema('FAQPage',{mainEntity:h.faq.map(x=>({'@type':'Question',name:x[0],acceptedAnswer:{'@type':'Answer',text:x[1]}}))})}));
  for(const r of ['aniimo','tier-list','database','tools','news','about','privacy']){const p=l.pages[r];const indexEntry=['aniimo','database'].includes(r)?`<a class="index-entry" href="${urlPath(l,'guides/confirmed-aniimo')}"><span><b>${esc(l.common.browseAllAniimo)}</b><small>${esc(l.common.aniimoIndexLead)}</small></span><em>→</em></a>`:'';const body=`<section class="article-shell"><article><p class="label">${esc(l.nav[r==='tier-list'?'tierList':r]||'ANIIMO GUIDE')}</p><h1>${esc(p.h1)}</h1><p class="lead">${esc(p.lead)}</p>${indexEntry}${(p.sections||[]).map(x=>`<h2>${esc(x[0])}</h2><p>${esc(x[1])}</p>`).join('')}${!['about','privacy','aniimo','database'].includes(r)?`<aside>${esc(l.common.comingAfterLaunch)}</aside>`:''}</article></section>`;write(outPath(l,r),doc({l,route:r,title:p.title,description:p.description,active:r,body,noindex:data.noindexRoutes.includes(r),schemaExtra:crumbs(l,[[l.nav.home,urlPath(l)],[p.h1,urlPath(l,r)]])}));}
  for(const r of ['contact','authors','terms']){const p=l.pages[r];const issueLink=r==='contact'?`<p><a class="primary" href="https://github.com/xuniyoucai-sudo/aniimogg/issues/new" rel="noopener">GitHub Issues ↗</a></p>`:'';const body=`<section class="article-shell"><article><p class="label">ANIIMO GUIDE</p><h1>${esc(p.h1)}</h1><p class="lead">${esc(p.lead)}</p>${p.sections.map(x=>`<h2>${esc(x[0])}</h2><p>${esc(x[1])}</p>`).join('')}${issueLink}</article></section>`;write(outPath(l,r),doc({l,route:r,title:p.title,description:p.description,active:'',body,schemaExtra:crumbs(l,[[l.nav.home,urlPath(l)],[p.h1,urlPath(l,r)]])}));}
  const mapP=l.pages.map;const mapBody=`<section class="listing-shell"><p class="label">IDYLL MAP</p><h1>${esc(mapP.h1)}</h1><p class="lead">${esc(mapP.lead)}</p><div class="region-grid">${data.regions.map(id=>`<article><b>${esc(l.nav.map)}</b><h2>${esc(l.regions[id][0])}</h2><p>${esc(l.regions[id][1])}</p></article>`).join('')}</div></section>`;write(outPath(l,'map'),doc({l,route:'map',title:mapP.title,description:mapP.description,active:'map',body:mapBody,schemaExtra:crumbs(l,[[l.nav.home,urlPath(l)],[mapP.h1,urlPath(l,'map')]])}));
  const gp=l.pages.guides,featured=['crossplay-cross-save','multiplayer','release-date-platforms','elements-roles'];const guideGroups=data.guideGroups.map(group=>`<section class="guide-group"><h2>${esc(l.guideLibrary[group.id])}</h2><div class="content-grid">${group.articles.map(id=>guideCard(l,id)).join('')}</div></section>`).join('');const guidesBody=`<section class="listing-shell"><p class="label">GUIDE LIBRARY</p><h1>${esc(gp.h1)}</h1><p class="lead">${esc(gp.lead)}</p><section class="popular-guides"><h2>${esc(l.guideLibrary.popular)}</h2><p>${esc(l.guideLibrary.popularLead)}</p><div class="content-grid">${featured.map(id=>guideCard(l,id)).join('')}</div></section><a class="index-entry" href="${urlPath(l,'guides/confirmed-aniimo')}"><span><b>${esc(l.common.browseAllAniimo)}</b><small>${esc(l.common.aniimoIndexLead)}</small></span><em>→</em></a>${guideGroups}</section>`;write(outPath(l,'guides'),doc({l,route:'guides',title:gp.title,description:gp.description,active:'guides',body:guidesBody,schemaExtra:crumbs(l,[[l.nav.home,urlPath(l)],[gp.h1,urlPath(l,'guides')]])}));
  for(const id of data.guideArticles){const g=l.guides[id],m=data.guideMeta[id],route='guides/'+id,cover=`/assets/guides/${id}-cover.webp`,visual=`/assets/guides/${id}-visual.webp`;const status=l.common[m.status==='beta'?'statusBeta':m.status==='release-tested'?'statusReleaseTested':'statusOfficial'];const sources=(g.sources||[]).map(x=>`<li><a href="${esc(x[1])}" rel="nofollow noopener" target="_blank">${esc(x[0])} ↗</a></li>`).join('');const sections=g.body.map((x,i)=>`<h2>${esc(x[0])}</h2><p>${esc(x[1])}</p>${i===1?`<figure class="guide-visual"><img src="${visual}" width="960" height="540" loading="lazy" alt="${esc(g.h1)} — ${esc(l.common.guideVisual)}"><figcaption>${esc(l.common.imageCredit)}</figcaption></figure>`:''}`).join('');const matrix=guideMatrix(g),articleFaq=guideFaq(g),faqSchema=g.faq?schema('FAQPage',{mainEntity:g.faq.map(x=>({'@type':'Question',name:x[0],acceptedAnswer:{'@type':'Answer',text:x[1]}}))}):'';const body=`<section class="article-shell"><a href="${urlPath(l,'guides')}">← ${esc(l.nav.guides)}</a><article><p class="label">${esc(l.common.informationStatus)} · ${esc(status)}</p><h1>${esc(g.h1)}</h1><p class="lead">${esc(g.description)}</p><div class="article-meta"><span><b>${esc(l.common.published)}</b>${m.published}</span><span><b>${esc(l.common.updated)}</b>${m.updated}</span><span><b>${esc(l.common.gameVersion)}</b>${esc(m.version)}</span><span><b>${esc(l.common.informationStatus)}</b>${esc(status)}</span></div><p class="byline">${esc(l.common.writtenBy)} · <a href="${urlPath(l,'authors')}">Aniimo Guide Editorial Team</a> · ${esc(l.common.lastReviewed)} ${m.updated}</p><figure class="guide-cover"><img src="${cover}" width="1200" height="675" fetchpriority="high" alt="${esc(g.h1)} — ${esc(l.common.guideCover)}"><figcaption>${esc(l.common.imageCredit)}</figcaption></figure>${sections}${matrix}${articleFaq}${sources?`<h2>${esc(l.common.officialSource)}</h2><ul class="source-list">${sources}</ul>`:''}<section class="change-log"><h2>${esc(l.common.changeLog)}</h2><ul><li><time datetime="${m.updated}">${m.updated}</time> — ${esc(l.common.changeVisual)}</li><li><time datetime="${m.published}">${m.published}</time> — ${esc(l.common.changePublished)}</li></ul></section><section class="related-guides"><h2>${esc(l.common.relatedGuides)}</h2><div>${m.related.map(x=>related(l,x)).join('')}</div></section></article></section>`;write(outPath(l,route),doc({l,route,title:g.title,description:g.description,active:'guides',body,type:'Article',image:cover,schemaExtra:schema('Article',{headline:g.h1,description:g.description,dateModified:m.updated,datePublished:m.published,image:data.domain+cover,author:{'@type':'Organization',name:'Aniimo Guide Editorial Team',url:abs(l,'authors')},mainEntityOfPage:abs(l,route),inLanguage:l.lang})+faqSchema+crumbs(l,[[l.nav.home,urlPath(l)],[l.nav.guides,urlPath(l,'guides')],[g.h1,urlPath(l,route)]])}));}
  const confirmedPath=outPath(l,'guides/confirmed-aniimo');const confirmedHtml=fs.readFileSync(confirmedPath,'utf8');fs.writeFileSync(confirmedPath,confirmedHtml.replace(`<h2>${esc(l.common.officialSource)}</h2>`,aniimoTable(l)+`<h2>${esc(l.common.officialSource)}</h2>`));
  const fp=l.pages.faq;const faqBody=`<section class="article-shell"><article><p class="label">FAQ</p><h1>${esc(fp.h1)}</h1><p class="lead">${esc(fp.lead)}</p>${l.faq.map((x,i)=>`<details${i===0?' open':''}><summary>${esc(x[0])}</summary><p>${esc(x[1])}</p></details>`).join('')}</article></section>`;write(outPath(l,'faq'),doc({l,route:'faq',title:fp.title,description:fp.description,active:'',body:faqBody,schemaExtra:schema('FAQPage',{mainEntity:l.faq.map(x=>({'@type':'Question',name:x[0],acceptedAnswer:{'@type':'Answer',text:x[1]}}))})}));
}

const sitemap=[];for(const route of [...data.routes.filter(x=>!data.noindexRoutes.includes(x)),...data.guideArticles.map(x=>'guides/'+x)]){const guideId=route.startsWith('guides/')?route.slice(7):'';const modified=data.guideMeta[guideId]?.updated||'2026-08-28';for(const locale of locales)sitemap.push(`<url><loc>${abs(locale,route)}</loc><lastmod>${modified}</lastmod>${locales.map(l=>`<xhtml:link rel="alternate" hreflang="${l.lang}" href="${abs(l,route)}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${abs(locales[0],route)}"/></url>`)}
write(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${sitemap.join('')}</urlset>`);
write(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\n\nSitemap: ${data.domain}/sitemap.xml\n`);
const errors={en:['Page not found | Aniimo Guide','That route has not been discovered','Return to the guide or choose another language.','Back to Aniimo Guide'],'zh-CN':['页面未找到｜Aniimo 伊莫攻略','这条探索路线尚未开放','页面可能已移动，请返回攻略首页。','返回伊莫攻略首页'],ja:['ページが見つかりません｜Aniimo攻略','このルートはまだ見つかっていません','ページが移動した可能性があります。攻略トップへ戻ってください。','Aniimo攻略トップへ']};
for(const l of locales){const e=errors[l.lang],body=`<section class="error-page"><div class="brand-mark">A</div><p class="label">404</p><h1>${e[1]}</h1><p>${e[2]}</p><a class="primary" href="${urlPath(l)}">${e[3]}</a></section>`;write(outPath(l,'404'),doc({l,route:'404',title:e[0],description:e[2],active:'',body,noindex:true}))}
fs.copyFileSync(path.join(root,'404','index.html'),path.join(root,'404.html'));
write(path.join(root,'_redirects'),`/world.html /zh-cn/map/ 301\n/faq.html /zh-cn/faq/ 301\n/about.html /zh-cn/about/ 301\n/privacy.html /zh-cn/privacy/ 301\n/guides/getting-started.html /zh-cn/guides/getting-started/ 301\n/guides/core-gameplay.html /zh-cn/guides/core-gameplay/ 301\n/guides/editorial-policy.html /zh-cn/guides/editorial-policy/ 301\n`);
console.log(`Generated ${locales.length} locales and ${sitemap.length} localized sitemap URLs.`);
