import fs from 'node:fs';import path from 'node:path';
const root=process.cwd(),html=[];const data=JSON.parse(fs.readFileSync(path.join(root,'src/data/site.json'),'utf8'));const aniimoIndex=JSON.parse(fs.readFileSync(path.join(root,'src/data/aniimo-index.json'),'utf8'));const legacy=new Set(['about.html','faq.html','privacy.html','world.html','guides/getting-started.html','guides/core-gameplay.html','guides/editorial-policy.html']);const walk=d=>{for(const n of fs.readdirSync(d)){if(['.git','src','node_modules'].includes(n))continue;const p=path.join(d,n),rel=path.relative(root,p);fs.statSync(p).isDirectory()?walk(p):p.endsWith('.html')&&!legacy.has(rel)&&html.push(p)}};walk(root);
let errors=[];for(const f of html){const s=fs.readFileSync(f,'utf8');for(const token of ['<title>','rel="canonical"','hreflang="en"','hreflang="zh-CN"','hreflang="ja"','hreflang="x-default"'])if(!s.includes(token))errors.push(`${f}: missing ${token}`);const lang=s.match(/<html lang="([^"]+)"/)?.[1];if(!lang)errors.push(`${f}: missing html lang`);for(const m of s.matchAll(/(?:href|src)="([^"]+)"/g)){let u=m[1];if(/^(https?:|#|mailto:)/.test(u))continue;u=u.split(/[?#]/)[0];let p=u.startsWith('/')?path.join(root,u):path.resolve(path.dirname(f),u);if(u.endsWith('/'))p=path.join(p,'index.html');if(!fs.existsSync(p))errors.push(`${f}: broken ${m[1]}`)}}
const en=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<details class="language-switcher"[\s\S]*?<\/details>/,'').replace(/<script[\s\S]*?<\/script>/g,'');if(/[\u4e00-\u9fff\u3040-\u30ff]/.test(en))errors.push('English homepage contains CJK UI text outside the language switcher');
const sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');for(const route of ['aniimo','tier-list','database']){if(!fs.readFileSync(path.join(root,route,'index.html'),'utf8').includes('content="noindex,follow"'))errors.push(`${route}: thin page must be noindex`);if(sitemap.includes(`<loc>https://aniimogg.com/${route}/</loc>`))errors.push(`${route}: noindex page present in sitemap`)}
const sitemapUrls=sitemap.match(/<url>/g)||[];if(sitemapUrls.length!==105)errors.push(`sitemap: expected 105 localized URLs, found ${sitemapUrls.length}`);for(const prefix of ['', 'zh-cn/', 'ja/'])for(const route of ['', 'guides/', 'guides/crossplay-cross-save/', 'guides/multiplayer/','guides/preorder-bundles/','guides/accessibility-features/','tools/','news/','news/global-launch-dates/','news/ps5-preorder-packs/','news/steam-language-support/'])if(!sitemap.includes(`<loc>https://aniimogg.com/${prefix}${route}</loc>`))errors.push(`sitemap: missing ${prefix}${route}`);
for(const route of ['contact','authors','terms'])if(!sitemap.includes(`<loc>https://aniimogg.com/${route}/</loc>`))errors.push(`${route}: missing from sitemap`);
for(const route of data.guideArticles){const m=data.guideMeta[route];if(!m)errors.push(`${route}: missing guide metadata`);for(const prefix of ['', 'zh-cn/', 'ja/']){const s=fs.readFileSync(path.join(root,prefix,'guides',route,'index.html'),'utf8');for(const token of ['class="article-meta"','class="guide-cover"','class="guide-visual"','width="1200" height="675"','width="960" height="540"','class="change-log"','class="related-guides"'])if(!s.includes(token))errors.push(`${prefix}${route}: missing ${token}`);if(!s.includes(`/assets/guides/${route}-cover.webp`))errors.push(`${prefix}${route}: missing guide cover reference`)}for(const kind of ['cover','visual'])if(!fs.existsSync(path.join(root,'assets/guides',`${route}-${kind}.webp`)))errors.push(`${route}: missing ${kind} image asset`);if(!sitemap.includes(`<loc>https://aniimogg.com/guides/${route}/</loc>`))errors.push(`${route}: missing from sitemap`)}
if(aniimoIndex.length!==94)errors.push(`Aniimo index expected 94 entries, found ${aniimoIndex.length}`);if(new Set(aniimoIndex.map(x=>x[0])).size!==aniimoIndex.length)errors.push('Aniimo index contains duplicate numbers');for(const prefix of ['', 'zh-cn/', 'ja/']){const s=fs.readFileSync(path.join(root,prefix,'guides/confirmed-aniimo/index.html'),'utf8');if((s.match(/<tbody><tr|<\/tr><tr/g)||[]).length!==94)errors.push(`${prefix}confirmed-aniimo: incomplete 94-row table`);if(!s.includes('wiki.aniimo.com/item/10002767'))errors.push(`${prefix}confirmed-aniimo: missing official entry links`);for(const token of ['class="index-search"','class="index-element"','class="index-role"','class="index-stage"','class="index-clear"','data-showing='])if(!s.includes(token))errors.push(`${prefix}confirmed-aniimo: missing filter ${token}`)}
for(const prefix of ['', 'zh-cn/', 'ja/']){const target=`/${prefix}guides/confirmed-aniimo/`;for(const page of ['index.html','aniimo/index.html','database/index.html','guides/index.html']){const s=fs.readFileSync(path.join(root,prefix,page),'utf8');if(!s.includes(`href="${target}"`))errors.push(`${prefix}${page}: missing confirmed Aniimo index link`)}for(const slug of ['elements-roles','evolution-forms','catching-twine']){const s=fs.readFileSync(path.join(root,prefix,'guides',slug,'index.html'),'utf8');if(!s.includes(`href="${target}"`))errors.push(`${prefix}guides/${slug}: missing related confirmed Aniimo link`)}}
for(const prefix of ['', 'zh-cn/', 'ja/'])for(const slug of ['crossplay-cross-save','multiplayer']){const s=fs.readFileSync(path.join(root,prefix,'guides',slug,'index.html'),'utf8');for(const token of ['class="article-faq"','"@type":"FAQPage"'])if(!s.includes(token))errors.push(`${prefix}guides/${slug}: missing ${token}`);if(slug==='crossplay-cross-save'&&!s.includes('class="support-matrix"'))errors.push(`${prefix}guides/${slug}: missing support matrix`)}
for(const prefix of ['', 'zh-cn/', 'ja/']){const s=fs.readFileSync(path.join(root,prefix,'guides/crossplay-cross-save/index.html'),'utf8');if(!s.includes('class="evidence-note"')||!s.includes('newslist/detail/100051'))errors.push(`${prefix}crossplay: missing event-vs-cross-save evidence`)}
for(const prefix of ['', 'zh-cn/', 'ja/']){const hub=fs.readFileSync(path.join(root,prefix,'guides/index.html'),'utf8');for(const token of ['class="popular-guides"','class="guide-group"','guides/crossplay-cross-save/','guides/multiplayer/','guides/release-date-platforms/'])if(!hub.includes(token))errors.push(`${prefix}guides: missing ${token}`);for(const slug of ['release-date-platforms','elements-roles']){const s=fs.readFileSync(path.join(root,prefix,'guides',slug,'index.html'),'utf8');if(!s.includes('class="support-matrix"'))errors.push(`${prefix}guides/${slug}: missing support matrix`);if(slug==='release-date-platforms'&&(!s.includes('class="article-faq"')||!s.includes('"@type":"FAQPage"')))errors.push(`${prefix}guides/${slug}: missing FAQ content/schema`)}}
for(const prefix of ['', 'zh-cn/', 'ja/']){const s=fs.readFileSync(path.join(root,prefix,'index.html'),'utf8');for(const token of ['home-explainer','home-faq','home-sources','"@type":"FAQPage"','wiki.aniimo.com'])if(!s.includes(token))errors.push(`${prefix}home: missing ${token}`);if((s.match(/<h2>/g)||[]).length<6)errors.push(`${prefix}home: insufficient H2 hierarchy`)}
for(const prefix of ['', 'zh-cn/', 'ja/']){const home=fs.readFileSync(path.join(root,prefix,'index.html'),'utf8');for(const token of ['class="event-alert section"','guides/pre-registration/','2026-09-02'])if(!home.includes(token))errors.push(`${prefix}home: missing current event or dynamic guide date ${token}`);const egg=fs.readFileSync(path.join(root,prefix,'guides/egg-heist/index.html'),'utf8');for(const token of ['class="support-matrix"','class="article-faq"','newslist/detail/100017','newslist/detail/100019','"@type":"FAQPage"'])if(!egg.includes(token))errors.push(`${prefix}egg-heist: missing beta timeline ${token}`);for(const slug of ['getting-started','core-gameplay']){const guide=fs.readFileSync(path.join(root,prefix,'guides',slug,'index.html'),'utf8');for(const token of ['2026-09-02','class="source-list"','playstation.com/en-us/games/aniimo'])if(!guide.includes(token))errors.push(`${prefix}${slug}: missing refreshed official content ${token}`)}}
for(const prefix of ['', 'zh-cn/', 'ja/']){for(const [route,tokens] of [['tools',['launch-countdown','readiness-check','store-grid']],['news',['news-feed','CollectionPage']],['map',['map-scope','guides/regions-world/']]]){const s=fs.readFileSync(path.join(root,prefix,route,'index.html'),'utf8');for(const token of tokens)if(!s.includes(token))errors.push(`${prefix}${route}: missing ${token}`)}}
for(const prefix of ['', 'zh-cn/', 'ja/']){for(const slug of ['global-launch-dates','ps5-preorder-packs','steam-language-support']){const s=fs.readFileSync(path.join(root,prefix,'news',slug,'index.html'),'utf8');for(const token of ['NewsArticle','datePublished','rel="alternate" type="application/rss+xml"'])if(!s.includes(token))errors.push(`${prefix}news/${slug}: missing ${token}`)}}
for(const [prefix,lang] of [['','en'],['zh-cn/','zh-CN'],['ja/','ja']]){const rss=fs.readFileSync(path.join(root,prefix,'rss.xml'),'utf8');for(const token of ['<rss version="2.0">',`<language>${lang}</language>`,'global-launch-dates','ps5-preorder-packs','steam-language-support'])if(!rss.includes(token))errors.push(`${prefix}rss.xml missing ${token}`);const page=fs.readFileSync(path.join(root,prefix,'news/index.html'),'utf8');if(!page.includes(`href="/${prefix}rss.xml"`))errors.push(`${prefix}news: wrong RSS discovery link`)}
for(const prefix of ['', 'zh-cn/', 'ja/']){const s=fs.readFileSync(path.join(root,prefix,'guides/accessibility-features/index.html'),'utf8');for(const token of ['class="support-matrix"','class="article-faq"','playstation.com/en-us/games/aniimo'])if(!s.includes(token))errors.push(`${prefix}accessibility-features: missing ${token}`)}
const llms=fs.readFileSync(path.join(root,'llms.txt'),'utf8');for(const stale of ['world.html','faq.html','繁体中文'])if(llms.includes(stale))errors.push(`llms.txt contains stale value ${stale}`);for(const route of ['tools/','map/','faq/'])if(!llms.includes(`aniimogg.com/${route}`))errors.push(`llms.txt missing ${route}`);
const headers=fs.readFileSync(path.join(root,'_headers'),'utf8');if(/\/assets\/\*[\s\S]*?immutable/.test(headers))errors.push('_headers: stable asset filenames must not use immutable caching');
console.log(`Checked ${html.length} HTML files.`);if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log('All multilingual checks passed.');
