import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),started=new Date(),data=JSON.parse(fs.readFileSync(path.join(root,'src/data/site.json'),'utf8')),news=JSON.parse(fs.readFileSync(path.join(root,'src/data/news.json'),'utf8'));
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(started),sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8'),checks=[];let failures=0;
const add=(name,ok,detail)=>{checks.push([name,`${ok?'PASS':'FAIL'} — ${detail}`]);if(!ok)failures++};
const imageCount=(sitemap.match(/<image:image>/g)||[]).length,urlCount=(sitemap.match(/<url>/g)||[]).length;
const latestGuide=Object.values(data.guideMeta).map(x=>x.updated).sort().at(-1),reviewAgeDays=Math.floor((started-new Date(`${latestGuide}T00:00:00+08:00`))/86400000);
add('Generated HTML',fs.existsSync(path.join(root,'index.html')),'homepage present');add('Sitemap',urlCount===129,`${urlCount} localized URLs (expected 129)`);add('Guide images',imageCount===69,`${imageCount} entries (expected 69)`);add('Latest guide review',reviewAgeDays<=14,`${latestGuide} · ${reviewAgeDays} day(s) old`);add('Latest news review',news.length>0,news.map(x=>x.updated).sort().at(-1));add('Official Aniimo snapshot',JSON.parse(fs.readFileSync(path.join(root,'src/data/aniimo-index.json'),'utf8')).length===94,'94 entries');
let commit='unknown';try{commit=execFileSync('git',['rev-parse','--short','HEAD'],{cwd:root,encoding:'utf8'}).trim()}catch{}
if(process.argv.includes('--live')){for(const route of ['/','/launch/','/server-status/','/codes/','/patch-notes/','/launch-verification/','/glossary/','/sitemap.xml','/robots.txt']){try{const response=await fetch(data.domain+route,{redirect:'manual'});add(`Live ${route}`,response.status===200,`${response.status} · ${response.headers.get('content-type')||'unknown type'}`)}catch(error){add(`Live ${route}`,false,error.message)}}try{const response=await fetch(data.domain+'/tools/',{redirect:'manual'});add('Live /tools/ redirect',[301,302,307,308].includes(response.status),`${response.status} → ${response.headers.get('location')||'missing location'}`)}catch(error){add('Live /tools/ redirect',false,error.message)}try{const response=await fetch(data.domain+'/',{redirect:'manual'});for(const header of ['strict-transport-security','content-security-policy','x-content-type-options','referrer-policy'])add(`Security ${header}`,Boolean(response.headers.get(header)),response.headers.get(header)||'missing')}catch(error){add('Security headers',false,error.message)}}
const finished=new Date(),duration=((finished-started)/1000).toFixed(1),overall=failures?'FAIL':'PASS';
const report=`# Aniimo.GG Daily Execution Report — ${today}\n\n## Run summary\n\n- **Overall:** ${overall}\n- **Started:** ${started.toISOString()}\n- **Finished:** ${finished.toISOString()}\n- **Duration:** ${duration}s\n- **Commit:** ${commit}\n- **Failures:** ${failures}\n\n## Automated checks\n\n${checks.map(x=>`- **${x[0]}:** ${x[1]}`).join('\n')}\n\n## External-data status\n\n- Google Search Console: not connected; query and impression analysis requires account access.\n- Cloudflare Analytics: not connected; traffic, cache-hit and Web Vitals analysis requires account access.\n- User search logs: not collected; the current static search does not transmit visitor queries.\n\n## Next launch checks\n\n- Recheck preload and platform-specific unlock notices.\n- Verify server names, queues and maintenance notices.\n- Execute the public-build checklist and replace Beta-only guidance only with repeatable evidence.\n`;
const output=path.join(root,'reports','daily',`${today}.md`);fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,report);console.log(report);console.log(`Saved ${path.relative(root,output)}`);process.exitCode=failures?1:0;
